### ISSUE TITLE
Doc: adding commands using direct access to the console application

### ISSUE THREAD

**Issue by schoenholz** [even-on-sunday/console#2]
The documentation states that adding commands is possible using direct access to the console via the `Pimple\Container::extend()` method:

```php
$app->extend('console', function($console, $app) {
    $console->add(new TestCommand());

    return $console;
});
```

Should the returned value of `::extend()` be stored in `$app['console']`?

```php
$app['console'] = $app->extend('console', function($console, $app) {
    $console->add(new TestCommand());

    return $console;
});
```

**Comment by bspellmeyer** [comment]
No, it is not necessary to store the returned value of ::extend(). Pimple reassignes the console definition with the closure defined in the ::extend() call. That's why it's important to actually return the Console instance inside of that closure.

**Comment by bspellmeyer** [comment]
No, it is not necessary to store the returned value of `::extend()`. Pimple reassignes the console definition with the closure defined in the `::extend()` call. That's why it's important to actually return the Console instance inside of that closure.

**Comment by schoenholz** [comment]
Okay.

**Comment by bspellmeyer** [comment]
Just testing *markdown* in mails.

**Comment by schoenholz** [comment]
**Test** markdown syntax *here*.

* and here
* here too

**Comment by bspellmeyer** [comment]
Testing Formatting!
